- id: poetry-export
  name: Poetry Export
  description: Prevent desync between poetry and requirements.txt
  entry: poetry-export
  language: python
  types: [text]
  files: requirements\.txt$
  additional_dependencies: [poetry]
